#!/bin/sh
# Startup script for ido2db-daemon
#
# chkconfig: 2345 95 05
# description: Icinga Database Objects daemon

# Source function library.
. /etc/rc.d/init.d/functions

prog=ido2db
user=icinga
prefix=/usr/local/icinga
exec=$prefix/bin/$prog
config=$prefix/etc/ido2db.cfg
piddir="/var/run"
lockdir="/var/lock/subsys"
pidfile="$piddir/$prog.pid"
lockfile="${lockdir}/$prog"

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: " 
    daemon --user $user $exec -c $config
    retval=$?
    [ $retval -eq 0 ] && touch $lockfile
    echo
    return $retval
}

stop() {
    if test "x`pidof $prog`" != x; then
        echo -n $"Stopping $prog: "
        killproc $prog
        echo
    fi
    retval=$?
    [ $retval -eq 0 ] && rm -f $lockfile $pidfile
    return $retval
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        status)
            status $prog
            ;;
        restart)
            stop
            start
            ;;
        condrestart)
            if test "x`pidof $prog`" != x; then
                stop
                start
            fi
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|condrestart|status}"
            exit 1

esac

exit $retval

